Adds support for pt mandatory QRCode generation
premium-minds/billy pull request #120
Opened 2020-10-31 20:11 UTC by trcdl

Adds pre support for ATCUD id on the series

2020-11-02 09:52 UTC, ajcamilo commented
@froque can you check this?

2020-11-02 12:32 UTC, ajcamilo requested changes

2020-11-02 12:32 UTC, ajcamilo commented on billy-gin/pom.xml
> +			<version>3.4.1</version>
put exclude of jcommand

2020-11-02 12:32 UTC, ajcamilo commented on billy-gin/src/main/java/com/premiumminds/billy/gin/services/impl/pdf/FOPPDFTransformer.java
> +            e.printStackTrace();
handle exceptions with care

2020-11-02 12:32 UTC, ajcamilo commented on billy-gin/src/main/java/com/premiumminds/billy/gin/services/impl/pdf/FOPPDFTransformer.java
> +        }finally {
we need some space

2020-11-02 12:32 UTC, ajcamilo commented on billy-gin/src/main/java/com/premiumminds/billy/gin/services/impl/pdf/FOPPDFTransformer.java
> +                log.warn("Could not delete file {}", path);
change to error level

2020-11-02 12:32 UTC, ajcamilo commented on billy-portugal-ebean/src/main/java/com/premiumminds/billy/portugal/services/export/qrcode/QRCodeDataGenerator.java
> +/*
update this

2020-11-03 14:16 UTC, ajcamilo requested changes

2020-11-03 14:16 UTC, ajcamilo commented on billy-gin/src/main/java/com/premiumminds/billy/gin/services/impl/pdf/FOPPDFTransformer.java
> +            new String(data.getBytes(StandardCharsets.UTF_8), StandardCharsets.UTF_8),
porque é que crias uma nova String de uma String?

2020-11-03 18:39 UTC, froque commented
[ESPECIFICAÇÕES TÉCNICAS Código de Barras Bidimensional Código QR](https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/Novas_regras_faturacao/Documents/Especificacoes_Tecnicas_Codigo_QR.pdf)

2020-11-03 21:10 UTC, froque commented
[Questões Frequentes - Outras Obrigações > Certif Softw > Código QR](https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/questoes_frequentes/Pages/faqs-00879.aspx)

2020-11-04 10:50 UTC, ajcamilo approved these changes

2020-11-04 11:15 UTC, merged